// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunGIPLmrsDkj51nn8dVKrrWt6xK4SOlo',
    appId: '1:471777658274:web:0e7e06fa25f21dbf8ddefb',
    messagingSenderId: '471777658274',
    projectId: 'zelow-dbf83',
    authDomain: 'zelow-dbf83.firebaseapp.com',
    storageBucket: 'zelow-dbf83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiniA-QWp53Mtdm6LyuySIBexL6JWY2vQ',
    appId: '1:471777658274:android:e6796263a142d5758ddefb',
    messagingSenderId: '471777658274',
    projectId: 'zelow-dbf83',
    storageBucket: 'zelow-dbf83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXcTJFs45XGk8TYBhq4u6hJslhIJuMKF0',
    appId: '1:471777658274:ios:8c0810e64d48276e8ddefb',
    messagingSenderId: '471777658274',
    projectId: 'zelow-dbf83',
    storageBucket: 'zelow-dbf83.firebasestorage.app',
    iosBundleId: 'com.example.zelow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXcTJFs45XGk8TYBhq4u6hJslhIJuMKF0',
    appId: '1:471777658274:ios:8c0810e64d48276e8ddefb',
    messagingSenderId: '471777658274',
    projectId: 'zelow-dbf83',
    storageBucket: 'zelow-dbf83.firebasestorage.app',
    iosBundleId: 'com.example.zelow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDunGIPLmrsDkj51nn8dVKrrWt6xK4SOlo',
    appId: '1:471777658274:web:e945bb70781def278ddefb',
    messagingSenderId: '471777658274',
    projectId: 'zelow-dbf83',
    authDomain: 'zelow-dbf83.firebaseapp.com',
    storageBucket: 'zelow-dbf83.firebasestorage.app',
  );
}
